<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DavidKuehn.Portfolio.ServiceDefaults\DavidKuehn.Portfolio.ServiceDefaults.csproj" />
    <ProjectReference Include="..\DavidKuehn.Portfolio.UI.Shared\DavidKuehn.Portfolio.UI.Shared.csproj" />
  </ItemGroup>

</Project>