<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DavidKuehn.Portfolio.Core\DavidKuehn.Portfolio.Core.csproj" />
    <ProjectReference Include="..\DavidKuehn.Portfolio.Infrastructure\DavidKuehn.Portfolio.Infrastructure.csproj" />
  </ItemGroup>

</Project>
